# == Schema Information
#
# Table name: acceptors
#
#  id               :integer          not null, primary key
#  name_acceptor    :string
#  bank_acceptor    :string
#  account_acceptor :string
#  key_acceptor     :string
#  mfo_acceptor     :string
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe AcceptorsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Acceptor. As you add validations to Acceptor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the sessions
  # in order to pass any filters (e.g. authentication) defined in
  # AcceptorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all acceptors as @acceptors" do
      acceptor = Acceptor.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:acceptors)).to eq([acceptor])
    end
  end

  describe "GET #show" do
    it "assigns the requested acceptor as @acceptor" do
      acceptor = Acceptor.create! valid_attributes
      get :show, {:id => acceptor.to_param}, valid_session
      expect(assigns(:acceptor)).to eq(acceptor)
    end
  end

  describe "GET #new" do
    it "assigns a new acceptor as @acceptor" do
      get :new, {}, valid_session
      expect(assigns(:acceptor)).to be_a_new(Acceptor)
    end
  end

  describe "GET #edit" do
    it "assigns the requested acceptor as @acceptor" do
      acceptor = Acceptor.create! valid_attributes
      get :edit, {:id => acceptor.to_param}, valid_session
      expect(assigns(:acceptor)).to eq(acceptor)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Acceptor" do
        expect {
          post :create, {:acceptor => valid_attributes}, valid_session
        }.to change(Acceptor, :count).by(1)
      end

      it "assigns a newly created acceptor as @acceptor" do
        post :create, {:acceptor => valid_attributes}, valid_session
        expect(assigns(:acceptor)).to be_a(Acceptor)
        expect(assigns(:acceptor)).to be_persisted
      end

      it "redirects to the created acceptor" do
        post :create, {:acceptor => valid_attributes}, valid_session
        expect(response).to redirect_to(Acceptor.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved acceptor as @acceptor" do
        post :create, {:acceptor => invalid_attributes}, valid_session
        expect(assigns(:acceptor)).to be_a_new(Acceptor)
      end

      it "re-renders the 'new' template" do
        post :create, {:acceptor => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested acceptor" do
        acceptor = Acceptor.create! valid_attributes
        put :update, {:id => acceptor.to_param, :acceptor => new_attributes}, valid_session
        acceptor.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested acceptor as @acceptor" do
        acceptor = Acceptor.create! valid_attributes
        put :update, {:id => acceptor.to_param, :acceptor => valid_attributes}, valid_session
        expect(assigns(:acceptor)).to eq(acceptor)
      end

      it "redirects to the acceptor" do
        acceptor = Acceptor.create! valid_attributes
        put :update, {:id => acceptor.to_param, :acceptor => valid_attributes}, valid_session
        expect(response).to redirect_to(acceptor)
      end
    end

    context "with invalid params" do
      it "assigns the acceptor as @acceptor" do
        acceptor = Acceptor.create! valid_attributes
        put :update, {:id => acceptor.to_param, :acceptor => invalid_attributes}, valid_session
        expect(assigns(:acceptor)).to eq(acceptor)
      end

      it "re-renders the 'edit' template" do
        acceptor = Acceptor.create! valid_attributes
        put :update, {:id => acceptor.to_param, :acceptor => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested acceptor" do
      acceptor = Acceptor.create! valid_attributes
      expect {
        delete :destroy, {:id => acceptor.to_param}, valid_session
      }.to change(Acceptor, :count).by(-1)
    end

    it "redirects to the acceptors list" do
      acceptor = Acceptor.create! valid_attributes
      delete :destroy, {:id => acceptor.to_param}, valid_session
      expect(response).to redirect_to(acceptors_url)
    end
  end

end
